### ISSUE TITLE
Albums with the same name but different parents should be allowed

### ISSUE THREAD

**Issue by LNT00** [andysh-uk/blue-twilight#58]
Create two albums, then try to create a sub-album with the same name in both albums, It's not allowed.
Unique album name should only be required in the same album, not across all albums.

![unique_albums](https://user-images.githubusercontent.com/32333032/31044831-b786648a-a5df-11e7-84c2-0782c94379e9.jpg)

**Comment by andysh-uk** [comment]
This is now possible in 2.1.1.
