### ISSUE TITLE
Album dropdown on manage page should become scroll-able when large number of albums

### ISSUE THREAD

**Issue by LNT00** [andysh-uk/blue-twilight#59]
On the manage page (/admin) when you have a large list of albums, the dropdown should become scrollable. Currently if the number of albums is larger than available screen, the page is enlarged instead of showing scroll inside the dropdown.

**Comment by pandy06269** [comment]
Sorry I’m not following this one. Please could you attach a screenshot showing what you mean?

**Comment by cozmalaurentiu** [comment]
Yes. There should be a max number of albums displayed in the dropdown, otherwise it will show all.

![albums](https://user-images.githubusercontent.com/32333032/31067780-4e37b932-a75d-11e7-9c14-23bc862f894b.jpg)

**Comment by cozmalaurentiu** [comment]
Also, like you can see above, the sorting is not really correct with numbers, but i think this is a really minor issue and can be ignored.

**Comment by pandy06269** [comment]
> Yes. There should be a max number of albums displayed in the dropdown, otherwise it will show all.

Perfect, thanks.

> Also, like you can see above, the sorting is not really correct with numbers, but i think this is a really minor issue and can be ignored.

This is because the album names are strings not numbers, so they get sorted as text not numerical.

**Comment by cozmalaurentiu** [comment]
I suggest showing all albums in the dropdown, but collapsed under parents. Basically only show the parents from homepage, and display the available child albums if you want to expand them.

Basically a combo box with albums displayed like tree view, similar to how folders are displayed.
![combotreebox](https://user-images.githubusercontent.com/32333032/31078794-1b5a3d1c-a78c-11e7-9711-960e872be4f6.png)

**Comment by andysh-uk** [comment]
Unfortunately nested menus are not officially supported by Bootstrap. I'm instead going to code in a couple of options for that selector.
