### ISSUE TITLE
Upload should not start when there are no files selected

### ISSUE THREAD

**Issue by LNT00** [andysh-uk/blue-twilight#65]
1. Go to Manage - Albums - click on an album - upload tab
2. Click on Upload button without selecting any files.

Uploading starts....with no files selected.

![upload_zero_files](https://user-images.githubusercontent.com/32333032/31124292-8c5cbed4-a84c-11e7-977a-bf992349032b.jpg)

**Comment by andysh-uk** [comment]
This has been resolved in 2.1.1
