### ISSUE TITLE
Update metadata should not remove photos it can't read

### ISSUE THREAD

**Issue by LNT00** [andysh-uk/blue-twilight#73]
I tried to update meta-data for some albums and in some occasions it failed, and removed the uploaded photos.
This is an issue, since most probably a retry would succeed, but in any case uploaded photos should not be removed.

This is the full failed response:

The following items could not be analysed and were removed:
DSC_2070: mkdir(): File exists
DSC_2069: mkdir(): File exists
DSC_2067: mkdir(): File exists
DSC_2079: fopen(/storage/app/analysis-queue/09vm0p0y0x/5kwdj10y9nitxoi50cyk.jpeg): failed to open stream: No such file or directory

In this case the process should skip these files and give the chance of a retry, or at lease ask for permission to delete those files.

**Comment by pandy06269** [comment]
Did it actually remove the record from the `photos` table or the physical file from the storage location? Ignore the path it’s given you in the error message - that’s a temporary storage path while it’s re-analysing. Check the place where the image files are physically stored (I.e. defined in your storage location.)

It definitely should not delete the originals! See your other ticket about upload/analyse failure - the fix in that should correct the reason why the metadata re-analyse failed.

**Comment by pandy06269** [comment]
I think the message still says it removed them because it’s the same screen used when analysing a new upload which does remove an uploaded file if the first analysis fails, but I don’t think it actually will have removed anything.

**Comment by LNT00** [comment]
The uploaded files were removed from storage, i searched for file names, not the analysis-queue location.

I will look further into this. maybe i can catch something to reproduce it with.

**Comment by LNT00** [comment]
No, actually the files are not removed from storage (local storage). Maybe replace the message with something friendlier? 
Also, although it fails for a certain file, metadata update is displayed as up-to-date for the album. A bit inconsistent.

**Comment by andysh-uk** [comment]
The message has been updated in 2.1.1.
